// utils/categories.js — 共享分类默认数据（手机端 & 平板端同一来源）
const DEFAULT_PERSONAL_CATEGORIES = [
  { id: 'p_1', name: '餐饮', emoji: '🍽', inOut: 'out' },
  { id: 'p_2', name: '交通', emoji: '🚗', inOut: 'out' },
  { id: 'p_3', name: '购物', emoji: '🛍', inOut: 'out' },
  { id: 'p_4', name: '娱乐', emoji: '🎮', inOut: 'out' },
  { id: 'p_5', name: '工资', emoji: '💰', inOut: 'in' },
  { id: 'p_6', name: '兼职', emoji: '💼', inOut: 'in' },
  { id: 'p_7', name: '投资', emoji: '📈', inOut: 'in' },
  { id: 'p_8', name: '租金', emoji: '🏠', inOut: 'in' },
  { id: 'p_9', name: '通讯', emoji: '📱', inOut: 'out' },
  { id: 'p_10', name: '医疗', emoji: '🏥', inOut: 'out' },
  { id: 'p_11', name: '外卖', emoji: '🛵', inOut: 'out' },
  { id: 'p_12', name: '打车', emoji: '🚕', inOut: 'out' },
  { id: 'p_13', name: '零食', emoji: '🍿', inOut: 'out' },
  { id: 'p_14', name: '快递', emoji: '📦', inOut: 'out' },
  { id: 'p_15', name: '水电', emoji: '💡', inOut: 'out' },
  { id: 'p_16', name: '奖金', emoji: '🎁', inOut: 'in' },
  { id: 'p_17', name: '稿费', emoji: '✍', inOut: 'in' },
  { id: 'p_18', name: '理财', emoji: '💎', inOut: 'in' },
  { id: 'p_19', name: '服装', emoji: '👗', inOut: 'out' },
  { id: 'p_20', name: '美妆', emoji: '💄', inOut: 'out' },
  { id: 'p_21', name: '宠物', emoji: '🐱', inOut: 'out' },
  { id: 'p_22', name: '运动', emoji: '⚽', inOut: 'out' },
  { id: 'p_23', name: '旅行', emoji: '🧳', inOut: 'out' },
  { id: 'p_24', name: '游戏', emoji: '🎲', inOut: 'out' },
  { id: 'p_25', name: '电影', emoji: '🎬', inOut: 'out' },
  { id: 'p_26', name: '摄影', emoji: '📷', inOut: 'out' },
  { id: 'p_27', name: '音乐', emoji: '🎵', inOut: 'out' },
  { id: 'p_28', name: '画画', emoji: '🎨', inOut: 'out' },
  { id: 'p_29', name: '烘焙', emoji: '🍰', inOut: 'out' },
  { id: 'p_30', name: '养花', emoji: '🌷', inOut: 'out' },
  { id: 'p_31', name: '红包', emoji: '🧧', inOut: 'in' },
  { id: 'p_32', name: '退款', emoji: '↩', inOut: 'in' },
  { id: 'p_33', name: '中奖', emoji: '🎯', inOut: 'in' },
  { id: 'p_34', name: '礼金', emoji: '🎀', inOut: 'in' },
  { id: 'p_35', name: '报销', emoji: '🧾', inOut: 'in' },
  { id: 'p_36', name: '补贴', emoji: '🪙', inOut: 'in' },
  { id: 'p_37', name: '代购', emoji: '🛒', inOut: 'payForward' },
  { id: 'p_38', name: '垫餐', emoji: '🍱', inOut: 'payForward' },
  { id: 'p_39', name: '垫车费', emoji: '🚕', inOut: 'payForward' },
  { id: 'p_40', name: '垫物料', emoji: '📦', inOut: 'payForward' },
  { id: 'p_41', name: '借款', emoji: '💰', inOut: 'payable' },
  { id: 'p_42', name: '欠款', emoji: '📝', inOut: 'payable' },
  { id: 'p_43', name: '分期', emoji: '🔄', inOut: 'payable' },
  { id: 'p_44', name: '赊账', emoji: '🧾', inOut: 'payable' },
  { id: 'p_45', name: '饮品', emoji: '🧋', inOut: 'out' },
  { id: 'p_46', name: '住房', emoji: '🏠', inOut: 'out' },
  { id: 'p_47', name: '人情', emoji: '🧧', inOut: 'out' },
  { id: 'p_48', name: '办公', emoji: '🖊', inOut: 'out' },
  { id: 'p_49', name: '金融', emoji: '🏦', inOut: 'out' },
  { id: 'p_50', name: '水果', emoji: '🍇', inOut: 'out' },
  { id: 'p_51', name: '蔬菜', emoji: '🥬', inOut: 'out' },
  { id: 'p_52', name: '日用品', emoji: '🧹', inOut: 'out' },
]

const DEFAULT_COMPANY_CATEGORIES = [
  { id: 'c_1', name: '采购', emoji: '📋', inOut: 'out' },
  { id: 'c_2', name: '回款', emoji: '💵', inOut: 'in' },
  { id: 'c_3', name: '差旅', emoji: '✈', inOut: 'out' },
  { id: 'c_4', name: '营收', emoji: '🏢', inOut: 'in' },
  { id: 'c_5', name: '招待', emoji: '🍷', inOut: 'out' },
  { id: 'c_6', name: '融资', emoji: '💳', inOut: 'in' },
  { id: 'c_7', name: '租金', emoji: '🏗', inOut: 'out' },
  { id: 'c_8', name: '分红', emoji: '💸', inOut: 'in' },
  { id: 'c_9', name: '物料', emoji: '📦', inOut: 'out' },
  { id: 'c_10', name: '物流', emoji: '🚚', inOut: 'out' },
  { id: 'c_11', name: '税费', emoji: '📊', inOut: 'out' },
  { id: 'c_12', name: '咨询', emoji: '🗣', inOut: 'in' },
  { id: 'c_13', name: '维修', emoji: '🔧', inOut: 'out' },
  { id: 'c_14', name: '软件', emoji: '💻', inOut: 'out' },
  { id: 'c_15', name: '保险', emoji: '🛡', inOut: 'out' },
  { id: 'c_16', name: '广告', emoji: '📢', inOut: 'out' },
  { id: 'c_17', name: '利息', emoji: '🏦', inOut: 'in' },
  { id: 'c_18', name: '培训', emoji: '📚', inOut: 'in' },
  { id: 'c_19', name: '办公用品', emoji: '🖊', inOut: 'out' },
  { id: 'c_20', name: '房租', emoji: '🏢', inOut: 'out' },
  { id: 'c_21', name: '水电物业', emoji: '🔌', inOut: 'out' },
  { id: 'c_22', name: '快递物流', emoji: '📮', inOut: 'out' },
  { id: 'c_23', name: '团建', emoji: '🎉', inOut: 'out' },
  { id: 'c_24', name: '招聘', emoji: '👔', inOut: 'out' },
  { id: 'c_25', name: '外包', emoji: '🤝', inOut: 'out' },
  { id: 'c_26', name: '服务器', emoji: '🖥', inOut: 'out' },
  { id: 'c_27', name: '域名', emoji: '🌐', inOut: 'out' },
  { id: 'c_28', name: '认证', emoji: '✅', inOut: 'out' },
  { id: 'c_29', name: '打印', emoji: '🖨', inOut: 'out' },
  { id: 'c_30', name: '保洁', emoji: '🧹', inOut: 'out' },
  { id: 'c_31', name: '合同款', emoji: '📝', inOut: 'in' },
  { id: 'c_32', name: '项目款', emoji: '📐', inOut: 'in' },
  { id: 'c_33', name: '服务费', emoji: '⚙', inOut: 'in' },
  { id: 'c_34', name: '佣金', emoji: '🤲', inOut: 'in' },
  { id: 'c_35', name: '赞助', emoji: '🎗', inOut: 'in' },
  { id: 'c_36', name: '政府补贴', emoji: '🏛', inOut: 'in' },
  { id: 'c_37', name: '差旅垫付', emoji: '✈', inOut: 'payForward' },
  { id: 'c_38', name: '采购垫付', emoji: '📋', inOut: 'payForward' },
  { id: 'c_39', name: '办公垫付', emoji: '🖥', inOut: 'payForward' },
  { id: 'c_40', name: '接待垫付', emoji: '🍷', inOut: 'payForward' },
  { id: 'c_41', name: '货款', emoji: '📦', inOut: 'payable' },
  { id: 'c_42', name: '工程款', emoji: '🏗', inOut: 'payable' },
  { id: 'c_43', name: '服务费', emoji: '⚙', inOut: 'payable' },
  { id: 'c_44', name: '租赁款', emoji: '🔑', inOut: 'payable' },
]

module.exports = {
  DEFAULT_PERSONAL_CATEGORIES,
  DEFAULT_COMPANY_CATEGORIES,
}
